on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
    # paths: ["apps/api"]

concurrency:
  cancel-in-progress: true
  group: "${{github.ref}}/deploy-api"

permissions:
  pull-requests: write

jobs:
  deploy-api:
    outputs:
      deploy-api-url: ${{ steps.cloudflare-pages-deployment.outputs.url }}
    environment:
      name: ${{ github.ref_name }}/api
      url: ${{ steps.cloudflare-pages-deployment.outputs.url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/api
            packages
      - uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm install
      - id: cloudflare-pages-deployment
        run: |
          NODE_ENV=development pnpm run deploy:api | tee ./deployment.log
          url=$(grep -o 'https://[^ ]*.pages.dev' deployment.log)
          echo "url=$url" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  comment:
    runs-on: ubuntu-22.04
    needs: [deploy-api]
    steps:
      - uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Deploy Preview"
      - uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Deploy Preview is ready!

            | Name |         Commit         |                      Link                      |
            | ---- | ---------------------- | ---------------------------------------------- |
            | api  | ${{ github.head_ref }} | ${{ needs.deploy-api.outputs.deploy-api-url }} |
