on:
  pull_request:
    types: ['closed']

permissions: write-all

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_TOKEN_APP_ID }}
          private-key: ${{ secrets.GH_TOKEN_PRIVATE_KEY }}
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await Promise.all(
              [
                '${{ github.ref_name }}/api',
                '${{ github.ref_name }}/website',
              ].map((environment_name) =>
                github.rest.repos.deleteAnEnvironment({
                  owner: '${{ github.repository_owner }}',
                  repo: '${{ github.event.repository.name }}',
                  environment_name,
                })
              )
            )
