on:
  pull_request:
    # types: ['closed']

permissions:
  contents: write
  deployments: write

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await Promise.all(
              [
                '${{ github.ref_name }}/api',
                '${{ github.ref_name }}/website',
              ].map((environment_name) =>
                github.rest.repos.deleteAnEnvironment({
                  owner: '${{ github.event.repository.owner }}',
                  repo: '${{ github.event.repository.name }}',
                  environment_name,
                })
              )
            )
